import { db } from "../lib/db";
import { users, forumCategories, forumTopics, forumReplies, activities, quests, questCompletions } from "../shared/schema";
import { eq, sql } from "drizzle-orm";

export async function seed() {
  const existingUsers = await db.select().from(users).limit(1);

  if (process.env.CLEAR_DB === "true") {
    console.log("Clearing existing data...");
    await db.delete(activities);
    await db.delete(forumReplies);
    await db.delete(forumTopics);
    await db.delete(forumCategories);
    await db.delete(questCompletions);
    await db.delete(quests);
    await db.delete(users);
  } else if (existingUsers.length > 0) {
    console.log("Data already exists. Use CLEAR_DB=true to overwrite.");
    return;
  }

  const seedUsers = await db
    .insert(users)
    .values([
      {
        id: "aa9c6919-a4ff-4fcc-acbf-aea76ffbd8e6",
        walletAddress: "0x742d35Cc6634C0532925a3b844Bc9e7595f2bD45",
        username: "Arjun Mehta",
        avatarUrl: "/images/avatar-arjun.jpg",
        bio: "Regional Lead for Western India. Scaling Web3 communities across Maharashtra and Gujarat.",
        skillTags: ["Strategic Partnerships", "Community Architecture", "Governance"],
        lensHandle: "arjun.lens",
        farcasterHandle: "arjunmehta",
        xHandle: "arjun_web3",
        telegramHandle: "arjun_m",
        isOnboarded: true,
        tier: "legend",
        role: "regional_lead",
        region: "Maharashtra",
        city: "Mumbai",
        referralCode: "ARJUN2026",
        referralsCount: 412,
        contentCount: 35,
        eventsCount: 18,
        sponsorLeadsCount: 12,
        totalPoints: 6240,
        questsCompleted: 24,
        stipend: 12000,
        college: "IIT Bombay",
      },
      {
        id: "ce5f5fb7-f27f-4019-bdce-eb7be7f95efb",
        walletAddress: "0x8ba1f109551bD432803012645Ac136ddd64DBA72",
        username: "Priya Sharma",
        avatarUrl: "/images/avatar-priya.jpg",
        bio: "Web3 Educator and Growth Specialist. Focused on onboarding students to Web3.",
        skillTags: ["Digital Marketing", "Educational Content", "Growth"],
        lensHandle: "priya.lens",
        farcasterHandle: "priyacrypto",
        xHandle: "priya_web3",
        telegramHandle: "priya_s",
        isOnboarded: true,
        tier: "ambassador",
        role: "contributor",
        region: "Maharashtra",
        city: "Pune",
        referralCode: "PRIYA2026",
        referralsCount: 214,
        contentCount: 56,
        eventsCount: 9,
        sponsorLeadsCount: 4,
        totalPoints: 3820,
        questsCompleted: 18,
        stipend: 5000,
        college: "COEP Pune",
      },
      {
        id: "59fb043c-df50-45e2-be38-50b9f7856c58",
        walletAddress: "0xdD2FD4581271e230360230F9337D5c0430Bf44C0",
        username: "Rahul Deshmukh",
        avatarUrl: "/images/avatar-rahul.jpg",
        bio: "Full-stack Developer and Solidity enthusiast. Building tools for student DeFi accessibility.",
        skillTags: ["Solidity", "React", "Smart Contracts"],
        lensHandle: "",
        farcasterHandle: "rahuldev",
        xHandle: "rahul_codes",
        telegramHandle: "rahul_d",
        isOnboarded: true,
        tier: "explorer",
        role: "contributor",
        region: "Maharashtra",
        city: "Mumbai",
        referralCode: "RAHUL2026",
        referralsCount: 82,
        contentCount: 14,
        eventsCount: 4,
        sponsorLeadsCount: 1,
        totalPoints: 1240,
        questsCompleted: 9,
        stipend: 0,
        college: "VJTI Mumbai",
      },
      {
        id: "e5540944-6b92-42f3-976f-256f7c95d4b9",
        walletAddress: "0x2546BcD3c84621e976D8185a91A922aE77ECEc30",
        username: "Sneha Iyer",
        avatarUrl: "/images/avatar-sneha.jpg",
        bio: "Visual Storyteller and Community Lead. Crafting narratives around blockchain adoption.",
        skillTags: ["Videography", "Creative Writing", "Branding"],
        lensHandle: "sneha.lens",
        farcasterHandle: "sneha",
        xHandle: "sneha_stories",
        telegramHandle: "sneha_i",
        isOnboarded: true,
        tier: "legend",
        role: "contributor",
        region: "Maharashtra",
        city: "Mumbai",
        referralCode: "SNEHA2026",
        referralsCount: 285,
        contentCount: 72,
        eventsCount: 11,
        sponsorLeadsCount: 6,
        totalPoints: 5120,
        questsCompleted: 21,
        stipend: 8000,
        college: "St. Xavier's College",
      },
      {
        id: "200a97ac-f7a7-4533-a8e9-b1a933a16892",
        walletAddress: "0xbDA5747bFD65F08deb54cb465eB87D40e51B197E",
        username: "Vikram Kulkarni",
        avatarUrl: "/images/avatar-vikram.jpg",
        bio: "DeFi Analyst and Campus Ambassador. Passionate about institutional research.",
        skillTags: ["Protocol Analysis", "Tokenomics", "Research"],
        lensHandle: "",
        farcasterHandle: "vikram",
        xHandle: "vikram_defi",
        telegramHandle: "vikram_k",
        isOnboarded: true,
        tier: "explorer",
        role: "contributor",
        region: "Karnataka",
        city: "Bangalore",
        referralCode: "VIKRAM2026",
        referralsCount: 56,
        contentCount: 9,
        eventsCount: 3,
        sponsorLeadsCount: 0,
        totalPoints: 840,
        questsCompleted: 7,
        stipend: 0,
        college: "RVCE Bangalore",
      },
      {
        id: "9df7d8ae-d690-46ac-bfe4-f05bdb67482f",
        walletAddress: "0x1234567890123456789012345678901234567890",
        username: "Ananya Nair",
        avatarUrl: "/images/avatar-ananya.jpg",
        bio: "Ecosystem Builder and Event Strategist. Bridging protocols and student talent.",
        skillTags: ["Ecosystem Growth", "Project Management", "Networking"],
        lensHandle: "ananya.lens",
        farcasterHandle: "ananya",
        xHandle: "ananya_ecosystem",
        telegramHandle: "ananya_n",
        isOnboarded: true,
        tier: "ambassador",
        role: "contributor",
        region: "Maharashtra",
        city: "Mumbai",
        referralCode: "ANANYA2026",
        referralsCount: 194,
        contentCount: 22,
        eventsCount: 14,
        sponsorLeadsCount: 8,
        totalPoints: 3420,
        questsCompleted: 15,
        stipend: 5000,
        college: "H.R. College",
      },
      {
        id: "fdd5e7bf-3d49-42f4-ac8b-cbc2e3ebafd9",
        walletAddress: "0x5555567890123456789012345678901234567890",
        username: "Karan Johar",
        avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
        bio: "Web3 content creator focused on Hindi tutorials. Reaching the next billion users.",
        skillTags: ["Hindi Content", "YouTube", "Growth"],
        lensHandle: "karan.lens",
        farcasterHandle: "karan",
        xHandle: "karan_web3",
        telegramHandle: "karan_j",
        isOnboarded: true,
        tier: "ambassador",
        role: "contributor",
        region: "Delhi",
        city: "New Delhi",
        referralCode: "KARAN2026",
        referralsCount: 165,
        contentCount: 45,
        eventsCount: 5,
        sponsorLeadsCount: 2,
        totalPoints: 2850,
        questsCompleted: 12,
        stipend: 3000,
        college: "Delhi University",
      },
      {
        id: "69b3825e-d03d-4d32-80ea-453528b12cd4",
        walletAddress: "0x6666567890123456789012345678901234567890",
        username: "Meera Reddy",
        avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
        bio: "Legendary contributor in Hyderabad. Leading the local developer community.",
        skillTags: ["Developer Relations", "Solidity", "Public Speaking"],
        lensHandle: "meera.lens",
        farcasterHandle: "meera",
        xHandle: "meera_codes",
        telegramHandle: "meera_r",
        isOnboarded: true,
        tier: "legend",
        role: "contributor",
        region: "Telangana",
        city: "Hyderabad",
        referralCode: "MEERA2026",
        referralsCount: 820,
        contentCount: 65,
        eventsCount: 15,
        sponsorLeadsCount: 10,
        totalPoints: 8400,
        questsCompleted: 30,
        stipend: 8000,
        college: "BITS Pilani Hyderabad",
      },
      {
        id: "13f62f24-cfae-4a9f-b1d9-6070e06a6fc5",
        walletAddress: "0x7777567890123456789012345678901234567890",
        username: "Siddharth Jain",
        avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop",
        bio: "Explorer focused on DAO governance and research.",
        skillTags: ["Governance", "DAO", "Research"],
        lensHandle: "",
        farcasterHandle: "sidjain",
        xHandle: "sid_dao",
        telegramHandle: "sid_j",
        isOnboarded: true,
        tier: "explorer",
        role: "contributor",
        region: "Rajasthan",
        city: "Jaipur",
        referralCode: "SID2026",
        referralsCount: 45,
        contentCount: 12,
        eventsCount: 2,
        sponsorLeadsCount: 0,
        totalPoints: 750,
        questsCompleted: 5,
        stipend: 0,
        college: "MNIT Jaipur",
      },
      {
        id: "a7868052-2f58-4bd8-9be6-d123e7a97d29",
        walletAddress: "0x8888567890123456789012345678901234567890",
        username: "Tanvi Gupta",
        avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop",
        bio: "Ambassador bridging the gap between design and Web3.",
        skillTags: ["UX Design", "Figma", "Branding"],
        lensHandle: "tanvi.lens",
        farcasterHandle: "tanvi",
        xHandle: "tanvi_design",
        telegramHandle: "tanvi_g",
        isOnboarded: true,
        tier: "ambassador",
        role: "contributor",
        region: "Gujarat",
        city: "Ahmedabad",
        referralCode: "TANVI2026",
        referralsCount: 180,
        contentCount: 38,
        eventsCount: 7,
        sponsorLeadsCount: 3,
        totalPoints: 3100,
        questsCompleted: 14,
        stipend: 3000,
        college: "NID Ahmedabad",
      },
      {
        id: "5c635143-0fe3-4cdb-ae6a-85024e5565b6",
        walletAddress: "0x9999567890123456789012345678901234567890",
        username: "Rohan Varma",
        avatarUrl: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150&h=150&fit=crop",
        bio: "Explorer running a Web3 club in Kochi.",
        skillTags: ["Community Building", "Events", "Malayalam Content"],
        lensHandle: "",
        farcasterHandle: "rohanv",
        xHandle: "rohan_web3",
        telegramHandle: "rohan_v",
        isOnboarded: true,
        tier: "explorer",
        role: "contributor",
        region: "Kerala",
        city: "Kochi",
        referralCode: "ROHAN2026",
        referralsCount: 92,
        contentCount: 15,
        eventsCount: 6,
        sponsorLeadsCount: 1,
        totalPoints: 1450,
        questsCompleted: 10,
        stipend: 0,
        college: "CUSAT Kochi",
      },
      {
        id: "60262115-2f46-40db-9c0f-60472773cb19",
        walletAddress: "0x0000567890123456789012345678901234567890",
        username: "Ishani Bose",
        avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop",
        bio: "Ambassador driving adoption in Kolkata colleges.",
        skillTags: ["Public Speaking", "Marketing", "Events"],
        lensHandle: "ishani.lens",
        farcasterHandle: "ishani",
        xHandle: "ishani_b",
        telegramHandle: "ishani_bose",
        isOnboarded: true,
        tier: "ambassador",
        role: "contributor",
        region: "West Bengal",
        city: "Kolkata",
        referralCode: "ISHANI2026",
        referralsCount: 172,
        contentCount: 28,
        eventsCount: 8,
        sponsorLeadsCount: 4,
        totalPoints: 2980,
        questsCompleted: 13,
        stipend: 3000,
        college: "Jadavpur University",
      },
    ])
    .returning();

  const seedCategories = await db
    .insert(forumCategories)
    .values([
      { id: "f40012dc-d41f-4735-84d7-d5674d1f6483", name: "General Discussion", description: "Open conversations about Web3.", slug: "general", icon: "MessageSquare", topicCount: 0 },
      { id: "5f8c42c0-6ad8-46cd-843e-152e7c8978d6", name: "Campus Outreach", description: "Strategies for campus workshops.", slug: "campus-outreach", icon: "GraduationCap", topicCount: 0 },
      { id: "b68ad721-af6d-42da-9858-386442857b5d", name: "Content & Growth", description: "Growth hacking and social tips.", slug: "content-growth", icon: "TrendingUp", topicCount: 0 },
      { id: "a5021a9d-237e-4f56-815c-a5f884e09a7a", name: "Sponsor Leads", description: "Deal strategies and partnerships.", slug: "sponsors", icon: "Handshake", topicCount: 0 },
      { id: "788033c3-234c-49bd-94d6-02fda61b6771", name: "Announcements", description: "Official program updates.", slug: "announcements", icon: "Megaphone", topicCount: 0 },
      { id: "aee87f5b-8e42-4e98-ba2e-04d45b1badcf", name: "Events", description: "Recaps and recaps.", slug: "events", icon: "Calendar", topicCount: 0 },
    ])
    .returning();

  const topicsData = [
    { categoryId: seedCategories[0].id, title: "Welcome to Insidr Contributor Hub!", content: "Introduce yourself here!", authorId: seedUsers[0].id, isPinned: true },
    { categoryId: seedCategories[1].id, title: "Campus Workshop Playbook", content: "proven playbook for Mumbai colleges.", authorId: seedUsers[0].id, isPinned: false },
    { categoryId: seedCategories[2].id, title: "X Content Strategy", content: "200+ referrals strategy.", authorId: seedUsers[1].id, isPinned: false },
    { categoryId: seedCategories[3].id, title: "Land Your First Sponsor", content: "Land Your First Sponsor Lead.", authorId: seedUsers[3].id, isPinned: true },
    { categoryId: seedCategories[4].id, title: "Q1 Goals Update", content: "crushing it!", authorId: seedUsers[0].id, isPinned: true },
    { categoryId: seedCategories[5].id, title: "IIT Bombay Workshop", content: "85 attendees!", authorId: seedUsers[0].id, isPinned: true },
    { categoryId: seedCategories[5].id, title: "ETH Mumbai Hackathon", content: "placed 2nd!", authorId: seedUsers[5].id, isPinned: false },
    { categoryId: seedCategories[5].id, title: "Pune Web3 Meetup", content: "40 contributors.", authorId: seedUsers[1].id, isPinned: false },
    { categoryId: seedCategories[0].id, title: "Future of DAOs", content: "What do you think?", authorId: seedUsers[8].id, isPinned: false },
    { categoryId: seedCategories[1].id, title: "Delhi Outreach", content: "Starting a club at DU.", authorId: seedUsers[6].id, isPinned: false },
    { categoryId: seedCategories[2].id, title: "YouTube Growth", content: "Hindi tutorials.", authorId: seedUsers[6].id, isPinned: false },
    { categoryId: seedCategories[0].id, title: "Web3 Design UX", content: "Figma tips.", authorId: seedUsers[9].id, isPinned: false },
    { categoryId: seedCategories[5].id, title: "Bangalore Meetup", content: "Tech capital vibes.", authorId: seedUsers[4].id, isPinned: false },
    { categoryId: seedCategories[1].id, title: "Hyderabad Dev Community", content: "Growing BITS camp.", authorId: seedUsers[7].id, isPinned: false },
    { categoryId: seedCategories[2].id, title: "Kolkata Marketing", content: "Growth hacks.", authorId: seedUsers[11].id, isPinned: false },
  ];

  const seedTopics = [];
  for (const topic of topicsData) {
    const [created] = await db.insert(forumTopics).values(topic).returning();
    seedTopics.push(created);
    await db.update(forumCategories).set({ topicCount: sql`${forumCategories.topicCount} + 1` }).where(eq(forumCategories.id, topic.categoryId));
  }

  const repliesData = [
    { topicId: seedTopics[0].id, content: "Excited to be here!", authorId: seedUsers[1].id },
    { topicId: seedTopics[0].id, content: "Hey everyone! Rahul here.", authorId: seedUsers[2].id },
    { topicId: seedTopics[1].id, content: "This is gold!", authorId: seedUsers[4].id },
    { topicId: seedTopics[2].id, content: "Thanks for sharing!", authorId: seedUsers[2].id },
    { topicId: seedTopics[3].id, content: "Exactly what I needed.", authorId: seedUsers[5].id },
    { topicId: seedTopics[4].id, content: "Amazing progress!", authorId: seedUsers[1].id },
    { topicId: seedTopics[8].id, content: "DAOs are the future.", authorId: seedUsers[0].id },
    { topicId: seedTopics[9].id, content: "Good luck with DU!", authorId: seedUsers[1].id },
    { topicId: seedTopics[10].id, content: "Great tutorials.", authorId: seedUsers[2].id },
    { topicId: seedTopics[11].id, content: "Design is key.", authorId: seedUsers[3].id },
    { topicId: seedTopics[12].id, content: "See you there!", authorId: seedUsers[5].id },
    { topicId: seedTopics[13].id, content: "Let's collab!", authorId: seedUsers[6].id },
    { topicId: seedTopics[14].id, content: "Nice growth tips.", authorId: seedUsers[7].id },
    { topicId: seedTopics[0].id, content: "Welcome aboard!", authorId: seedUsers[3].id },
    { topicId: seedTopics[5].id, content: "Great energy!", authorId: seedUsers[4].id },
    { topicId: seedTopics[6].id, content: "Congrats team!", authorId: seedUsers[0].id },
    { topicId: seedTopics[7].id, content: "Pune vibes!", authorId: seedUsers[2].id },
    { topicId: seedTopics[8].id, content: "Governance matters.", authorId: seedUsers[9].id },
    { topicId: seedTopics[9].id, content: "Join the Delhi group.", authorId: seedUsers[6].id },
    { topicId: seedTopics[10].id, content: "Share the link.", authorId: seedUsers[11].id },
  ];

  for (const reply of repliesData) {
    await db.insert(forumReplies).values(reply);
    await db.update(forumTopics).set({ replyCount: sql`${forumTopics.replyCount} + 1`, lastReplyAt: new Date() }).where(eq(forumTopics.id, reply.topicId));
  }

  await db.insert(quests).values([
    { title: "First 10 Referrals", description: "Get 10 signups.", category: "referrals", points: 100, targetCount: 10, difficulty: "easy", isActive: true },
    { title: "50 Referral Milestone", description: "Reach 50 referrals.", category: "referrals", points: 300, targetCount: 50, difficulty: "medium", isActive: true },
    { title: "Referral Champion", description: "Hit 200 signups.", category: "referrals", points: 800, targetCount: 200, difficulty: "hard", isActive: true },
    { title: "First Content Post", description: "Create a post on X.", category: "content", points: 50, targetCount: 1, difficulty: "easy", isActive: true },
    { title: "Content Creator", description: "Publish 10 pieces.", category: "content", points: 250, targetCount: 10, difficulty: "medium", isActive: true },
    { title: "Host a Workshop", description: "Organize an event.", category: "events", points: 200, targetCount: 1, difficulty: "medium", isActive: true },
    { title: "Event Organizer", description: "Successfully organize 5 events.", category: "events", points: 500, targetCount: 5, difficulty: "hard", isActive: true },
    { title: "Land Sponsor Lead", description: "Generate a sponsor lead.", category: "sponsors", points: 300, targetCount: 1, difficulty: "hard", isActive: true },
    { title: "Club Collaboration", description: "Partner with a club.", category: "community", points: 150, targetCount: 1, difficulty: "medium", isActive: true },
    { title: "Telegram Moderator", description: "Moderate for 30 days.", category: "community", points: 200, targetCount: 30, difficulty: "medium", isActive: true },
    { title: "Video Tutorial", description: "Create a tutorial.", category: "content", points: 150, targetCount: 1, difficulty: "medium", isActive: true },
    { title: "Mega Hackathon", description: "Help organize a hackathon.", category: "events", points: 1000, targetCount: 1, difficulty: "hard", isActive: true },
    { title: "Twitter Thread", description: "Write a 5-post thread.", category: "content", points: 100, targetCount: 1, difficulty: "easy", isActive: true },
    { title: "Newsletter Feature", description: "Get featured in a newsletter.", category: "content", points: 500, targetCount: 1, difficulty: "hard", isActive: true },
    { title: "Regional Meetup", description: "Organize a city meetup.", category: "events", points: 300, targetCount: 1, difficulty: "medium", isActive: true },
  ]);

  const activityData: Array<{ type: string; userId: string; metadata: Record<string, unknown> }> = seedUsers.map(u => ({ type: "new_contributor", userId: u.id, metadata: { username: u.username, tier: u.tier } }));
  activityData.push({ type: "tier_up", userId: seedUsers[0].id, metadata: { username: seedUsers[0].username, newTier: "legend" } });
  activityData.push({ type: "quest_completed", userId: seedUsers[0].id, metadata: { username: seedUsers[0].username, questTitle: "Referral Champion" } });
  activityData.push({ type: "event_organized", userId: seedUsers[0].id, metadata: { username: seedUsers[0].username, eventName: "IIT Bombay Workshop", topicId: seedTopics[5].id, imageUrl: "/images/event-tech-workshop_1.jpg", contentPreview: "Amazing turnout today! Over 80 students joined our intro to Web3 workshop at IIT Bombay. The energy was incredible." } });
  activityData.push({ type: "event_organized", userId: seedUsers[5].id, metadata: { username: seedUsers[5].username, eventName: "ETH Mumbai Hackathon", topicId: seedTopics[6].id, imageUrl: "/images/event-tech-workshop_2.jpg", contentPreview: "Our team placed 2nd at ETH Mumbai! Huge thanks to the organizers for such a smooth event. See you at the next one!" } });
  activityData.push({ type: "event_organized", userId: seedUsers[1].id, metadata: { username: seedUsers[1].username, eventName: "Pune Web3 Meetup", topicId: seedTopics[7].id, imageUrl: "/images/event-tech-workshop_3.jpg", contentPreview: "Had a great time at the Pune Web3 Meetup yesterday. Met so many passionate builders in the ecosystem." } });
  activityData.push({ type: "event_organized", userId: seedUsers[7].id, metadata: { username: seedUsers[7].username, eventName: "Hyderabad Meetup", topicId: seedTopics[13].id, imageUrl: "/images/event-tech-workshop_4.jpg", contentPreview: "The Hyderabad community is growing fast! We discussed everything from L2s to DAO governance today." } });

  await db.insert(activities).values(activityData);

  console.log("Seed data expanded successfully");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
